[package]
name = "twenty-forty-eight"
version = "0.1.0"
authors = ["Sasha Manzyuk <manzyuk@fb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.13"
rand = "0.7.2"
